spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OATH2_DOMAIN}
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
  port: 9999
  error:
    include-stacktrace: never
